# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import summarization_pb2 as summarization__pb2


class SummarizationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SummarizeText = channel.unary_unary(
        '/SummarizationService/SummarizeText',
        request_serializer=summarization__pb2.Speech.SerializeToString,
        response_deserializer=summarization__pb2.SummarizedSpeech.FromString,
        )


class SummarizationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SummarizeText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SummarizationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SummarizeText': grpc.unary_unary_rpc_method_handler(
          servicer.SummarizeText,
          request_deserializer=summarization__pb2.Speech.FromString,
          response_serializer=summarization__pb2.SummarizedSpeech.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SummarizationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
